### ISSUE TITLE
GKE: Could not determine issuer for ingress due to bad annotations

### ISSUE THREAD

**Issue by kehao95** [netdata/helmchart#133]
Hi I was trying to deploy the helm chart to my cluster running in GKE. 
Then I couldn't get the netdata-parent node up and running. It's always showing `pending`

After some digging I found the log
```
Could not determine issuer for ingress due to bad annotations: failed to determine issuer name to be used for ingress resource
```
I'll try to solve it and provide solution if I find one. But I think maybe we should improve the doc about this.

**Comment by knatsakis** [comment]
Hi @kehao95,

Could you provide the helm configuration that you used?

Thanks.

**Comment by kehao95** [comment]
I used default configs. 
```
git clone https://github.com/netdata/helmchart.git netdata-helmchart
helm show values ./netdata-helmchart > netdata.values.yaml
helm install -n netdata netdata ./netdata-helmchart -f netdata.values.yaml
```

The ingress part config was:
```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - netdata.k8s.local
#  tls:
#    - secretName: netdata-tls
#      hosts:
#        - netdata.k8s.local
```


btw I'm okay without ingress so I disabled it.
