### ISSUE TITLE
Supporting Springboot2 and Redis module (since they are go.d.plugin now)?

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/helmchart#188]
Hi thanks for the lib! I wonder whether the springboot2 module can be auto discovered? Because it is also a go.d plugin, so IMHO it should be able to be configured easily.

Espeically, when I look at the [source code](https://github.com/netdata/go.d.plugin/blob/master/modules/springboot2/springboot2.go), it seems to be *soooo* simple that it seems to have no extra magic on its own! Thus IMHO it could be easily added?

Thanks!

**Comment by ilyam8** [comment]
Hi @fzyzcjy! 

Let me give you a brief description how servicy discovery works:
 - it is a separate container running within netdata pod.
 - [that is service discovery app](https://github.com/ilyam8/agent-service-discovery#service-discovery).
 - that is [default sd configuration](https://github.com/netdata/helmchart/blob/master/charts/netdata/sdconfig/child.yml).

`sd` gets notified about all created/deleted pods. It created **a target per port per container per pod**. The target contains the following fields - https://github.com/ilyam8/agent-service-discovery#pod-role

And we use those fields to identify an application and to create a specific configuration (go.d plugin configuration).

For instance: if the port is 80 or 8080 and `httpd*` patterns matches container image, we assume that it is apache running inside the container. And we tag the target with `apache` tag.

https://github.com/netdata/helmchart/blob/33fc823fe4650d64c1483a39b273e1d5430f77e2/charts/netdata/sdconfig/child.yml#L22-L23

Later we use those tags to build appropriate configuration - ok if there is `apache` tag lets create `apache` collector job.

https://github.com/netdata/helmchart/blob/33fc823fe4650d64c1483a39b273e1d5430f77e2/charts/netdata/sdconfig/child.yml#L116-L120

---

I hope you understand the flow. Back to Springboot2 - we need something to identify Springboot2 app (we have https://github.com/ilyam8/agent-service-discovery#pod-role fields).

**Comment by fzyzcjy** [comment]
@ilyam8 Hi thanks for the reply! So IMHO we can just create a custom annotation and let the users to put the annotation on their apps. Just like the prometheus annotation, we can do something like:

```
      annotations:
        netdata.springboot2/scrape: 'true'
        netdata.springboot2/port: '80'
```

Or, maybe another way is, add a configurable section in the `Values.yaml` of this helmchart, and let the user to decide what annotations to add.

**Comment by fzyzcjy** [comment]
By the way, I suddently see that there is a new Redis plugin in go.d.plugin! Thus IMHO we could easily do auto discover for it?

**Comment by fzyzcjy** [comment]
OK I have done the springboot2:

```
tag:
  - name: "Applications"
    selector: unknown
    tags: -unknown applications
    match:
      - tags: tom_springboot2
        expr: '{{ eq (get .Annotations "tom_netdata_auto_discover_mode") "springboot2" }}'

...
build:
   ...
      - selector: tom_springboot2
        template: |
          - module: springboot2
            name: springboot2-{{.TUID}}
            url: http://{{.Address}}/actuator/prometheus
```
