### ISSUE TITLE
Clarification of how to override alarm rules

### ISSUE THREAD

**Issue by zzvara** [netdata/helmchart#199]
Dear Community,

I have been struggling with how to override the alarm rules on our Netdata deployment running on 3 of our Kubernetes clusters. We are using the Cloud as well to integrate all dashboards into one. Pretty neat.

However, could not find a clear description of how to override the rules that drive alarms. Here is an example:

![image](https://user-images.githubusercontent.com/8371789/113334981-a7e76e80-9324-11eb-8aea-989689605cf4.png)

Story: On our clusters, we host all kinds of workloads, including data processing (Spark), web services, Kubeless functions, load balancers, a bunch of operators, Seldon models, and the list can continue. We integrated alarms with Discord - but getting a lot of false positives, thus, currently, Netdata is really not much use to us. On a single-node Dockerized environment we learned to update alarm rules as described in the documentation, by updating rules under `health.d` directory.

Problem: `health.d` is empty in the case of both child and parent Pod containers. I checked around the Pod, including the volumes mounted, and found no records of where these rules are.

Setup: this is how we deploy Netdata:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: netdata
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    repository: https://netdata.github.io/helmchart/
    name: netdata
    version: 3.6.3
  releaseName: netdata
  values:
    parent:
      database:
        storageclass: local
      alarms:
        storageclass: local
      configs:
        stream:
          data: |
            [11111111-2222-3333-4444-555555555555]
              enabled = yes
              history = 36000
              default memory mode = save
              health enabled by default = auto
              allow from = *
        health:
          data: |
            # Configuration for alarm notifications
            #
            # This configuration is used by: alarm-notify.sh
            # changes take effect immediately (the next alarm will use them).
            #
            ...
            ...
```

I was looking around in the chart documentation to figure out where to put the alarm rules, but could not find any place.

I'd be happy to be pointed to resources and told what to do. :-)

Thanks,

**Comment by ilyam8** [comment]
Hi, @zzvara 👋 Sorry for the late reply.

>  but getting a lot of false positives

Could you provide some examples? We can tune our default alarms if there are any problems.

>  On a single-node Dockerized environment we learned to update alarm rules as described in the documentation, by updating rules under health.d directory.

Same works for k8s. For instance, if I want to overwrite [health.d/cgroups.conf](https://github.com/netdata/netdata/blob/master/health/health.d/cgroups.conf) on the parent node:

 - create overwrite.yaml with my `cgroups.conf`

<details>
<summary>overwrite.yaml [Click]</summary>

```YAML
parent:
  configs:
    health_cgroups:
      enabled: true
      path: /etc/netdata/health.d/cgroups.conf
      data: |
        template: cgroup_10min_cpu_usage
               on: cgroup.cpu_limit
            class: Cgroups
        component: CPU
             type: Utilization
               os: linux
            hosts: *
           lookup: average -10m unaligned
            units: %
            every: 1m
             warn: $this > (($status >= $WARNING)  ? (75) : (85))
             crit: $this > (($status == $CRITICAL) ? (85) : (95))
            delay: down 15m multiplier 1.5 max 1h
             info: average cgroup CPU utilization over the last 10 minutes
               to: sysadmin

         template: cgroup_ram_in_use
               on: cgroup.mem_usage
            class: Cgroups
        component: Memory
             type: Utilization
               os: linux
            hosts: *
             calc: ($ram) * 100 / $memory_limit
            units: %
            every: 10s
             warn: $this > (($status >= $WARNING)  ? (80) : (90))
             crit: $this > (($status == $CRITICAL) ? (90) : (98))
            delay: down 15m multiplier 1.5 max 1h
             info: cgroup memory utilization
               to: sysadmin
```


</details>

 - apply it when installing/updating netdata helmchart
