### ISSUE TITLE
No k8s data showing up in cloud

### ISSUE THREAD

**Issue by rjbaat** [netdata/helmchart#204]
Hi All, 
I setup the Netdata Agent by the helm chart following the default setup and video on YouTube: https://www.youtube.com/watch?v=-VFq_VtBwOc

There is an child and parent agent and data is showing on the cloud. But It looks like only performance metrics for the operation of netdata itself and its plugins is showing up. So only: web, statsd and aclk.

What do I need to do to get also the whole k8s data showing up?

**Comment by ilyam8** [comment]
Hi @rjbaat 👋 

You have only netdata parent claimed, correct?

**Comment by rjbaat** [comment]
Yes I put in the claim token twice. For both parent and child in the helm chart. Like: 

```
---
  child: 
    claiming: 
      enabled: "true"
      rooms: "same_room_id_from_cloud"
      token: "same_token_id_from_cloud"
      configs:
        netdata:
          data: |
            [global]
              memory mode = dbengine
              history = 3600
            [health]
              enabled = no
  parent: 
    alarms: 
      volumesize: "1Gi"
    claiming: 
      enabled: "true"
      rooms: "same_room_id_from_cloud"
      token: "same_token_id_from_cloud"

```

**Comment by rjbaat** [comment]
btw iam seeing more when doing a port forward like: 

`kubectl port-forward svc/netdata 19999:19999 -n netdata`

Could it be that the cloud can't reach the child nodes?

**Comment by rjbaat** [comment]
Anyone? How can I get the child data visible on the cloud? Is there a firewall rulle I need to open or something? So data from the child can be streamed to the cloud or browser?

**Comment by digitalcraig** [comment]
I'm having this exact same issue. I see a parent node only in cloud even though I specified the token and room for both. Only web, statsd, and aclk show under parent as well.

**Comment by alechartung** [comment]
I think I ran into this as well when upgrading from 1.29.x to 1.30.1.

**Comment by ilyam8** [comment]
Hi, guys 👋 Sorry for the late response.

Yes, we need children instances claimed in order to see them on the Cloud. Cloud fetches data directly from the claimed nodes - despite the fact that the children's data is stored on the parent node we need children to have that data too.

So we need:
 - set claiming parameters: enabled, token, and rooms.
 - change memory mode to `dbengine` or `ram`.

Default is `none`, it means no data stored on the child instance => claimed OK, but no metrics on the Cloud.

https://github.com/netdata/helmchart/blob/7f32dada6c881122ecbab79ec19df398dea3cfa8/charts/netdata/values.yaml#L248-L254

---

@rjbaat there is a mistake in your _override.yaml_: see configs.netdata.data - it is under claiming.

Should be

```YAML
child:
  claiming:
    enabled: true
    rooms: "ROOMS"
    token: "TOKEN"
  configs:
    netdata:
      data: |
        [global]
          # ram or dbengine, not none
          memory mode = ram
          history = 3600
        [health]
          enabled = no
```

---

Another minor error: _enabled_ is boolean, not string, so it is `true` or `false`, not `"true"` or `"false"`.

**Comment by ilyam8** [comment]
The following is tested on my k8s cluster in GKE (it is a potato cluster, so I need to set _resources.requests_, you don't need it).

<details>
<summary>override.yaml [Click]</summary>

```YAML
sd:
  child:
    resources:
      requests:
        cpu: 1m
        memory: 1Mi

child:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
  claiming:
    enabled: true
    rooms: "ROOMS"
    token: "TOKEN"
  configs:
    netdata:
      data: |
        [global]
          memory mode = ram
          history = 3600
        [health]
          enabled = no
parent:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
  claiming:
    enabled: true
    rooms: "ROOMS"
    token: "TOKEN"
```

</details>

<img width="1344" alt="Screenshot 2021-05-04 at 13 41 54" src="https://user-images.githubusercontent.com/22274335/116992321-7fb1ad80-acde-11eb-85b8-042fae9d38da.png">
