### ISSUE TITLE
[Docs] Example showing how to add plugin

### ISSUE THREAD

**Issue by themadmrj** [netdata/helmchart#217]
Having installed netdata on my k8s cluster with the helm chat, I'm looking to connect my remote database to it (and my uwsgi/asgi app), but I couldn't find a comprehensive example showing how to configure the default `override.yaml` to add such a service. I think that would be very helpful (I for one would need it).

**Comment by ilyam8** [comment]
Hi @themadmrj 

Can you elaborate a bit? What plugin do you want to add? Why do you need to connect to your remote database? What database is that?

**Comment by themadmrj** [comment]
Thanks for the reply @ilyam8 
I want to add the python/postgres [plugin](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/postgres) to monitor my remote postgresql database. I would like to check requests/sec or /min or memory usage.

**Comment by ilyam8** [comment]
Does _remote_ mean external to the Kubernetes cluster?

**Comment by themadmrj** [comment]
Yes

**Comment by ilyam8** [comment]
@fzyzcjy could you help here? Looks like the same problem you solved in https://github.com/netdata/helmchart/issues/189#issuecomment-772933216

**Comment by fzyzcjy** [comment]
@ilyam8 sure. here is my config:

```
# NOTE put it in PARENT, NOT CHILD!!!
parent:
  configs:
    mysql:
      enabled: true
      # NOTE use the go.d one, NOT THE python.d one
      path: /etc/netdata/go.d/mysql.conf
      data: |
        jobs:
          - name: external-mysql
            # feel free to put whatever you want, i personally prefer some templates
            dsn: '{{ .Values.mysql.username }}:{{ .Values.mysql.password }}@tcp(external-mysql:{{ .Values.mysql.port }})/'
```

where my mysql host is a service like mentioned by ilyam8:

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-mysql.fullname" . }} # say it is called "external-mysql"
  labels:
    {{- include "external-mysql.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.externalName }}
  ports:
    - port: {{ .Values.service.port }}
```
