### ISSUE TITLE
Helm upgrade fails 3.7.33 to 3.7.34, 3.7.35 or 3.7.36

### ISSUE THREAD

**Issue by pcm32** [netdata/helmchart#323]
Starting from:

```
NAME           	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                       	APP VERSION
netdata        	default  	1       	2022-11-16 15:52:08.753301 +0000 UTC	deployed	netdata-3.7.33              	v1.36.1
```

doing:
```
helm upgrade -f netdata/override.yaml netdata netdata/netdata
```

produces:
```
Error: UPGRADE FAILED: template: netdata/templates/service.yaml:1:14: executing "netdata/templates/service.yaml" at <.Values.parent.enabled>: nil pointer evaluating interface {}.enabled
```

the override file is what I copied from the page to add nodes in the war room. The same happens if I limit the upgrade to versions 3.7.34 and 3.7.35 (from 3.7.33).

What should I do to update the installation? Thanks!

**Comment by ilyam8** [comment]
Hi, @pcm32. It is because of the wrong indentation.

Instead of 

```yaml
parent:
claiming:
  enabled: true
  token: some_value
  rooms: 
  
child:
claiming:
  enabled: true
  token: some_value
  rooms: 
```

should be

```yaml
parent:
  claiming:
    enabled: true
    token: some_value
    rooms: 
  
child:
  claiming:
    enabled: true
    token: some_value
    rooms: 
```
