### ISSUE TITLE
Include default requests/limits for child pods

### ISSUE THREAD

**Issue by ohthehugemanatee** [netdata/helmchart#348]
Since a good deal of netdata's value is in keeping its' footprint as small as possible, and instances are stateless, adding default limits for child pods seem to make sense. I would include parent and k8s-state too, but AFAIK those are relative to the size/complexity of the cluster and therefore hard to predict.

Setting resource requests is just good practice. Setting limits prevent runaway processes.

Based on the [docs](https://learn.netdata.cloud/docs/deployment-in-production/how-to-optimize-the-netdata-agent-s-performance#resources-required-by-a-default-netdata-installation) I suggest defaulting the child to 

```
resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    memory: 250Mi
```
