### ISSUE TITLE
can't create /tmp/as.log: Permission denied

### ISSUE THREAD

**Issue by happysalada** [netdata/helmchart#43]
master node goes into CrashLoopBackOff
Here are the logs
```
2019-09-08 02:06:05: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'FATAL' 'netdata:MAIN' '0023@registry/r:registry_init  /13'                    │
│ /usr/libexec/netdata/plugins.d/anonymous-statistics.sh: line 28: can't create /tmp/as.log: Permission denied                                                                      │
│ 2019-09-08 02:06:06: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...                                                                                         │
│ 2019-09-08 02:06:06: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'ERROR' '-'                                                             │
│ /usr/libexec/netdata/plugins.d/anonymous-statistics.sh: line 28: can't create /tmp/as.log: Permission denied                                                                      │
│ 2019-09-08 02:06:06: netdata INFO  : MAIN : EXIT: cleaning up the database...                                                                                                     │
│ 2019-09-08 02:06:06: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...                                                                                                  │
│ 2019-09-08 02:06:06: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...  
```

I'm using two volumes with access mode ReadWriteOnce with rook and ceph fs
Should I have used ReadWriteMany?

**Comment by paulkatsoulakis** [comment]
> master node goes into CrashLoopBackOff
> Here are the logs
> 
> ```
> 2019-09-08 02:06:05: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'FATAL' 'netdata:MAIN' '0023@registry/r:registry_init  /13'                    │
> │ /usr/libexec/netdata/plugins.d/anonymous-statistics.sh: line 28: can't create /tmp/as.log: Permission denied                                                                      │
> │ 2019-09-08 02:06:06: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...                                                                                         │
> │ 2019-09-08 02:06:06: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'ERROR' '-'                                                             │
> │ /usr/libexec/netdata/plugins.d/anonymous-statistics.sh: line 28: can't create /tmp/as.log: Permission denied                                                                      │
> │ 2019-09-08 02:06:06: netdata INFO  : MAIN : EXIT: cleaning up the database...                                                                                                     │
> │ 2019-09-08 02:06:06: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...                                                                                                  │
> │ 2019-09-08 02:06:06: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...  
> ```
> 
> I'm using two volumes with access mode ReadWriteOnce with rook and ceph fs
> Should I have used ReadWriteMany?

Hello @happysalada, thanks for reaching out!

If i would put my 2c on this, i would carefully read the access modes usage here: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes and then re-validate the set up.

In case you can't figure it out with this information, we will need more details regarding your set up so that we can try to reproduce your use case further and provide more accurate feedback

Thanks again, talk soon!

**Comment by happysalada** [comment]
yeah my bad for the too sparse info.
I'm running kubernetes 1.15.3 on baremetal with flannel networking
using rook ceph fs storage
storage.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
    # clusterID is the namespace where the rook cluster is running
    clusterID: rook-ceph
    # Ceph pool into which the RBD image shall be created
    pool: replicapool

    # RBD image format. Defaults to "2".
    imageFormat: "2"

    # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
    imageFeatures: layering

    # The secrets contain Ceph admin credentials.
    csi.storage.k8s.io/provisioner-secret-name: rook-ceph-csi
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    csi.storage.k8s.io/node-stage-secret-name: rook-ceph-csi
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

    # Specify the filesystem type of the volume. If not specified, csi-provisioner
    # will set default as `ext4`.
    csi.storage.k8s.io/fstype: xfs

# Delete the rbd volume when a PVC is deleted
reclaimPolicy: Delete
```

I create two persistent volumes
pv-alarms.yaml
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: netdata-alarms-pv
  labels:
    type: local
spec:
  storageClassName: netdata-alarms
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```
pv-database.yaml
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: netdata-database-pv
  labels:
    type: local
spec:
  storageClassName: netdata-database
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

I then install the operator with  the following values.yaml file
```
replicaCount: 1

image:
  repository: netdata/netdata
  tag: v1.15.0
  pullPolicy: Always

sysctlImage:
  enabled: false
  repository: alpine
  tag: latest
  pullPolicy: Always
  command: []

service:
  type: ClusterIP
  port: 19999

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - netdata.k8s.local
#  tls:
#    - secretName: netdata-tls
#      hosts:
#        - netdata.k8s.local

rbac:
  create: true

serviceAccount:
  create: true
  name: netdata


master:
  resources: {}
    # limits:
    #  cpu: 4
    #  memory: 4096Mi
    # requests:
    #  cpu: 4
    #  memory: 4096Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env: {}

  podLabels: {}

  podAnnotations: {}

  database:
    persistence: true
    storageclass: "netdata-database"
    volumesize: 2Gi

  alarms:
    persistence: true
    storageclass: "netdata-alarms"
    volumesize: 100Mi

  configs:
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [11111111-2222-3333-4444-555555555555]
          enabled = yes
          history = 3600
          default memory mode = save
          health enabled by default = auto
          allow from = *
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          memory mode = save
          bind to = 0.0.0.0:19999
        [plugins]
          cgroups = no
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = no
          go.d = no
          node.d = no
          apps = no
          proc = no
          idlejitter = no
          diskspace = no
    health:
      enabled: false
      path: /etc/netdata/health_alarm_notify.conf
      data: |
        SEND_EMAIL="NO"
        SEND_SLACK="YES"
        SLACK_WEBHOOK_URL=""
        DEFAULT_RECIPIENT_SLACK=""
        role_recipients_slack[sysadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[domainadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[dba]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[webmaster]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[proxyadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[sitemgr]="${DEFAULT_RECIPIENT_SLACK}"
    example:
      enabled: false
      path: /etc/netdata/health.d/example.conf
      data: |
        alarm: example_alarm1
          on: example.random
        every: 2s
        warn: $random1 > (($status >= $WARNING)  ? (70) : (80))
        crit: $random1 > (($status == $CRITICAL) ? (80) : (90))
        info: random
          to: sysadmin

slave:
  resources: {}
    # limits:
    #  cpu: 4
    #  memory: 4096Mi
    # requests:
    #  cpu: 4
    #  memory: 4096Mi

  nodeSelector: {}

  tolerations:
    - operator: Exists
      effect: NoSchedule

  affinity: {}

  podLabels: {}

  podAnnotationAppArmor:
    enabled: true

  podAnnotations: {}

  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          memory mode = none
        [health]
          enabled = no
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [stream]
          enabled = yes
          destination = netdata:19999
          api key = 11111111-2222-3333-4444-555555555555
          timeout seconds = 60
          buffer size bytes = 1048576
          reconnect delay seconds = 5
          initial clock resync iterations = 60
    coredns:
      enabled: true
      path: /etc/netdata/go.d/coredns.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:9153/metrics
    kubelet:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubelet.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10255/metrics
    kubeproxy:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubeproxy.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10249/metrics

  env: {}

````

(it's the default file except, I have tried disabling the healthcheck to see what was wrong. and I disabled ingress. I also had to change the storage class for database and alarms. The pvc are bound without problem.

Let me know if you need more informations.
