### ISSUE TITLE
K8S/Helm: How to install plugins?

### ISSUE THREAD

**Issue by spanktar** [netdata/helmchart#477]
Just like #231, I find it extremely difficult to understand how to install plugins using the helm chart.

My goal is to install this:
Plugin: go.d.plugin Module: nvidia_smi

So I would...enable `go.d` in `parent.configs.netdata.data` like so?

```
parent:
  configs:
    netdata:
      data: |
        [global]
          hostname = {{ .Values.parent.hostname }}
        [db]
          mode = dbengine
        [plugins]
          cgroups = no
          tc = no
»        enable running new plugins = yes
          check for new plugins every = 72000
          python.d = no
          charts.d = no
»        go.d = yes
          node.d = no
          apps = no
          proc = no
          idlejitter = no
          diskspace = no
```

And in the child as well?

Then, how do I add a new `go.d`-type plugin? Just add its module name?

```
parent:
  configs:
    netdata:
      data: |
...
        [plugins]
           nvidia_smi = yes
```

The [docs for `go.d`](https://learn.netdata.cloud/docs/developer-and-contributor-corner/external-plugins/go.d.plugin/) say to edit `go.d.conf`, but I don't know how to accomplish this with the Helm Chart.

**SIDENOTE:**

The format of these values, being `data: |` is very inconvenient, as to update/add/edit it, you have to replicate the entire block, which includes `Values`, which can't be passed via `values.yaml` replacement. It seems to me this should be in a map format, like so:

```
parent:
  configs:
    netdata:
      data:
        global:
          hostname: {{ .Values.parent.hostname }}
        db:
          mode: dbengine
        plugins:
          cgroups: no
...
```

With this format, it would be trivial to add or update new entries via `values.yaml`, for example:

```
parent:
  configs:
    netdata:
      data:
        plugins:
           "enable running new plugins": yes
           "go.d": yes
```
