### ISSUE TITLE
RFC: Long-term metrics storage. Move to only Statefulset?

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#61]
I'd love to find a way to persist at least `/var/lib/netdata/registry/netdata.public.unique.id`, in order to allow long-term retention of the metrics collected from each node, regardless of pod restarts. That file contains the MACHINE_GUID and previous efforts to keep it the same have failed. 

If I read https://github.com/kubernetes/kubernetes/issues/78902 correctly, with daemonset we're stuck at the time with [hostpath volume mounts](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath), which requires root access and generally looks like just a hack. 

From what I've read, it looks like the only proper way to do this is by converting the slave nodes from a daemonset to a statefulset. I understand there are caveats though, and it would be a significant change, so I'd appreciate feedback before moving ahead with this. 

@varyumin @kam1kaze @ktsakalozos @karuppiah7890 @joshw123 @charlieegan3 @josecv can any of you provide insights?

**Comment by josecv** [comment]
hrmm here's my hot take from my experience with k8s -- maybe others will disagree :)

imho this does not feel like a natural fit for a statefulset, nor have i seen this done with a statefulset in the past. Guaranteeing a pod running on each node while using a statefulset is really not ergonomic. You're trying to

a) use affinity rules to ensure that no two pods _ever_ end up on the same node,

b) coerce the user into always scaling the statefulset so that it has the same number of replicas as there are nodes (a coercion that I think becomes increasingly painful as ops teams grow and the engineer on call who grew the node pool isn't up to speed with the monitoring setup -- you're bound to eventually miss a node), and

c) guarantee that, when a new node is added and the statefulset is scaled up, the pv is going to come up in a volume zone that is compatible with that of the new node. In my experience different pvc implementations will deal with this more or less gracefully. Some will always work out, others will happily bring up a pv in the wrong AZ and then leave the pod stuck in pending because it is unable to attach the volume to the node.

i'm not sure that those requirements make it actually worth it to use a statefulset for this. I think there's a few workarounds for this

1) use an [init container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) coupled with some centralized mechanism to initialize and save the machine identifier. To give a very naive example, imagine an init container that uses an S3-compatible bucket to store a hostmap to guid mapping, fetches it on startup and places it under `/var/lib/netdata/registry/netdata.public.unique.id` so that the actual netdata container effectively always has the same id.

2) use an init container to deterministically generate the guid. This looks like what [this commit reverted](https://github.com/netdata/helmchart/pull/60) -- i think the issues caused by that had to do with it being implemented as a postStart hook instead of an init container.

3) go with the statefulset, BUT implement some kind of `slave-manager` system that will actively listen for new hosts/pods and ensure that the replica count/distribution of pods is always acceptable. i guess under certain circumstances this slave manager would have to be willing to nuke a guid if the PV manager on the cluster screwed up.

4) bite the bullet with the `hostPath`. tbqh, i do not think this is that bad. netdata is being installed as a fairly low level, close to metal, monitoring solution. in my experience it is not uncommon for this sort of thing to come with special permissions. If I understand the current helm chart correctly, netdata looks to be running in god mode already as it mounts the docker socket and `/proc` into the pod, so what's another hostpath among friends in this situation?

**Comment by cakrit** [comment]
This is awesome @josecv , I had never heard of init containers and it looks like the 2nd option would indeed be really good. The thing that bugs me about #4 is that I don't want netdata *writing* anything on the host. Not sure what type of permissions we have on that socket today tbh, but we definitely don't write anything and never should. 

We do have to figure out how we can get a predictable UUID from the node's hostname, which is not what python's `uuid.uuid3` was doing. I had missed that it gives you a *random* UUID. The discussion in https://github.com/netdata/netdata/issues/7265 should settle that though, I'll get on it to see what people wrote there.

**Comment by cakrit** [comment]
One sec though, the 4th option could work without netdata having to write anything. If as an admin I have access to the node's filesystem, I can just put a `netdata.public.unique.id` with a UUID somewhere on the node, we mount that directory and allow netdata only read access to it. Right? I suppose that the init container could do the same, just look for a specific file that contains the UUID  on a configurable place on the node and just put that UUID in the proper place for netdata to find it.  The caveat with this approach is that it required an action from the user, but the other options have caveats as well...

**Comment by josecv** [comment]
Hmm you're right that an administrator could easily write the uuid, then netdata just reads it. I guess that has a similar disadvantage as the statefulset though, in that it requires user intervention when a new node is added. On the other hand, I guess astute users could easily write things like cloud init scripts that generate the uuid automagically, but that will not be the same for every cluster, so it's kinda tricky to advise users on how to do this correctly.

I think on second thought though, I'd prefer the 2nd option since as you say it doesn't require writing to the node or manual user intervention. Not a crypto expert so not sure what you'd need to make the uuid deterministic but I guess if that can be surmounted the rest is easy.

**Comment by josecv** [comment]
hmm i guess there's another option which is to leverage the existing uid on the node k8s object.

All kubernetes objects already have a UUID -- it's under `metadata.uid`. So if you had an init container with permissions to _read_ from the kubernetes api, this init container could basically just `kubectl get node $THE_NODE_IM_ON -o jsonpath='{.metadata.uid}' > netdata.public.unique.id`. This would guarantee that it's always the same uid, as long as it's the same node.

I guess the disadvantage of this is that you'd need permissions on the cluster. Now, in terms of netdata itself you only really need read permissions. But the nature of helm is such that emitting [clusterroles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole) (which i think you'd need to do since k8s `node` objects are not namespaced) requires the tiller that installs this chart to be superuser on the cluster.

**Comment by cakrit** [comment]
Very interesting idea! I will check next week, I'm in a week long meetup.

**Comment by cakrit** [comment]
Finally got some time to look into this. We can definitely use `.metadata.uid` and our helmchart already includes the required access. 

We'll need to either extend https://github.com/netdata/netdata/blob/master/daemon/get-kubernetes-labels.sh.in, or add a new script, just to retrieve the node UUID. The netdata daemon will also need to be extended.

**Comment by varyumin** [comment]
I will be able to rewrite this bash script to Golang with SDK Kubernetes
client and write Dockerfile and extend it

вт, 21 янв. 2020 г. в 20:00, Chris Akritidis <notifications@github.com>:

**Comment by varyumin** [comment]
I wrote code on GOlang, I need a few time  to review on best practice  and after review, I will upload code to my repo a sent  URL to my repo

**Comment by ilyam8** [comment]
Not a specialist, just thinking out loud. 

Could following work?:

- we have slave config-map
- init container gets local node uid
- and puts it into slave configmap

```yaml
node-<NODE-NAME>-uid: value
```
- we mount that value to the slave `/var/lib/netdata/registry/netdata.public.unique.id`

___

We can make it dynamic using `subPathExpr`

```cmd
0 ilyam:playground $  kubectl explain deployment.spec.template.spec.containers.volumeMounts.subPathExpr
KIND:     Deployment
VERSION:  apps/v1

FIELD:    subPathExpr <string>

DESCRIPTION:
     Expanded path within the volume from which the container's volume should be
     mounted. Behaves similarly to SubPath but environment variable references
     $(VAR_NAME) are expanded using the container's environment. Defaults to ""
     (volume's root). SubPathExpr and SubPath are mutually exclusive.
```

___

example

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: default
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location = /stub_status {
            stub_status;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
    ## hehe

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      volumes:
        - name: config
          configMap:
            name: nginx-config-map
            defaultMode: 0444
      containers:
        - name: nginx
          image: nginx
          env:
            - name: ENV
              value: default.conf
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPathExpr: $(ENV)

---
```

but instead of 

```yaml
env:
  - name: ENV
     value: default.conf
```

we will use

```yaml
env:
  - name: MY_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
```

**Comment by cakrit** [comment]
Using an init container sounds like a good idea to me, I just don't know about the config map. A shared volume could work very well though, as [in this example](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container).

The great thing about this idea is that it doesn't need changes to the netdata daemon.

**Comment by ilyam8** [comment]
It seems you are right, i think init container that fethes local node uid is a way to go, it looks like an robust and easy way to achieve the goal. ConfigMap/shared volume is detail and both will do. 

i think i try to fix the issue 😄

**Comment by ilyam8** [comment]
Using `emptyDir` volume is easier then configMap, `busybox` is enough for initContainer.

This works: a Pod with init container that fetched node uid

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: init-test
spec:
  serviceAccountName: node-viewwer
  initContainers:
    - name: install
      image: busybox
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      command:
        - "/bin/sh"
      args:
        - "-c"
        - '
        TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
        URL="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/nodes/${MY_NODE_NAME}";
        HEADER="Authorization: Bearer ${TOKEN}";

        DATA=$(wget -q -T 5 --no-check-certificate --header "${HEADER}" -O - "${URL}");
        [ -z "${DATA}" ] && exit 1;

        UID=$(echo "${DATA}" | grep -m 1 uid | grep -o ":.*," | tr -d ": \",");
        [ -z "${UID}" ] && exit 1;

        echo "${UID}" > /work-dir/uid;
        '
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
  containers:
    - name: busybox
      image: busybox
      command: [ "sleep" ]
      args: [ "infinity" ]
      volumeMounts:
        - name: workdir
          mountPath: /etc/node_uid
  volumes:
    - name: workdir
      emptyDir: {}
```

___

0 ilyam:playground $ kubectl exec -it init-test cat /etc/node_uid/uid
50d0f031-a82e-4f98-bb0e-f865b71390fa

**Comment by ilyam8** [comment]
I dont really like having bash inside args (no syntax highlighting, checking), but it feels like it doesnt worth to create something (repo + image) for something so simple at least for now.

I could make it in such way but make it optional. What do you think @cakrit ?

**Comment by cakrit** [comment]
If this works, let's do a PR and we'll get additional feedback. I'm personally not worried about code in the configuration.

**Comment by varyumin** [comment]
Are you sure you choose the right UID? And didn't confuse UID? Because in manifest node we have 2 kinds of UID. Firs it's UID of Kubernetes, second UID of Node. Example manifest by node:

```
apiVersion: v1
kind: Node
metadata:
  annotations:
...
  labels:
    ...
  selfLink: /api/v1/nodes/dc-wks-ceph-c8349d69-01
  uid: cda0f4ee-896b-11e9-b816-fa163e99a8c7
spec:
  ...
status:
 ...
  images:
 ... 
  nodeInfo:
    architecture: amd64
    bootID: 4355d9dc-2849-424f-8b80-8d76376dd739
    containerRuntimeVersion: docker://18.9.5
    kernelVersion: 4.15.0-76-generic
    kubeProxyVersion: v1.14.1
    kubeletVersion: v1.14.1
    machineID: 626be7e4892b4a55a642050afff283df
    operatingSystem: linux
    osImage: Ubuntu 18.04.2 LTS
    systemUUID: 626BE7E4-892B-4A55-A642-050AFFF283DF
```
I think. the correct choose is `systemUUID: 626BE7E4-892B-4A55-A642-050AFFF283DF`
