### ISSUE TITLE
netdata with efs provisioner

### ISSUE THREAD

**Issue by masterkain** [netdata/helmchart#64]
I know that others had this issue:

```
│ netdata 2019-12-08 07:03:36: netdata ERROR : MAIN : Cannot open the file /var/lib/netdata/health.silencers.json (errno 2, No such file or directory)
│ netdata 2019-12-08 07:03:36: netdata FATAL : MAIN :Cannot create directory '/var/lib/netdata/registry'. # : Invalid argument
```

but I can't solve it, trying to use efs-provisioner, PVCs are created fine so I'm not sure the storageclass is the issue.

my helm release file:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: netdata
  namespace: netdata
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: netdata
  chart:
    git: https://github.com/netdata/helmchart.git
    path: "."
    ref: master
  values:
    [snip]
    master:
      database:
        persistence: true
        storageclass: efs
        volumesize: 2Gi
      alarms:
        persistence: true
        storageclass: efs
        volumesize: 2Gi
```
