### ISSUE TITLE
CoreDNS URL

### ISSUE THREAD

**Issue by bitva77** [netdata/helmchart#66]
I believe the CoreDNS URL should be set to 

`- url: http://kube-dns.kube-system.svc.cluster.local:9153/metrics`

It's currently set to localhost in the default configmap but I think the service URL should be used instead.  At least in my kubeadm setup, port 9153 isn't exposed locally but rather via the service URL.

Only possible downside is that every netdata slave will be querying the same metrics from CoreDNS.  I could see concern about large clusters with lots of nodes causing issues with this kind of setup.

Saying that, maybe it's something better handled by the master?

**Comment by ilyam8** [comment]
Isn't this related to data collection?

https://github.com/netdata/go.d.plugin/blob/94156e5061d02407628689e79817a7f8489e242b/config/go.d/coredns.conf#L183-L184

**Comment by bitva77** [comment]
I think the Helm chart values.yaml file needs to be updated as well though:

```
    coredns:
      enabled: true
      path: /etc/netdata/go.d/coredns.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:9153/metrics
```

unless I'm misunderstanding something :)
